// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/caiiomp/vehicle-platform-sales/src/core/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SaleRepository is an autogenerated mock type for the SaleRepository type
type SaleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sale
func (_m *SaleRepository) Create(ctx context.Context, sale entity.Sale) (*entity.Sale, error) {
	ret := _m.Called(ctx, sale)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Sale) (*entity.Sale, error)); ok {
		return rf(ctx, sale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Sale) *entity.Sale); ok {
		r0 = rf(ctx, sale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Sale) error); ok {
		r1 = rf(ctx, sale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByVehicleID provides a mock function with given fields: ctx, vehicleID
func (_m *SaleRepository) GetByVehicleID(ctx context.Context, vehicleID string) (*entity.Sale, error) {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for GetByVehicleID")
	}

	var r0 *entity.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Sale, error)); ok {
		return rf(ctx, vehicleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Sale); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, vehicleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx
func (_m *SaleRepository) Search(ctx context.Context) ([]entity.Sale, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []entity.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Sale, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Sale); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusByPaymentID provides a mock function with given fields: ctx, paymentID, status, soldDate
func (_m *SaleRepository) UpdateStatusByPaymentID(ctx context.Context, paymentID string, status string, soldDate *time.Time) (*entity.Sale, error) {
	ret := _m.Called(ctx, paymentID, status, soldDate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByPaymentID")
	}

	var r0 *entity.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) (*entity.Sale, error)); ok {
		return rf(ctx, paymentID, status, soldDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) *entity.Sale); ok {
		r0 = rf(ctx, paymentID, status, soldDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *time.Time) error); ok {
		r1 = rf(ctx, paymentID, status, soldDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSaleRepository creates a new instance of SaleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaleRepository {
	mock := &SaleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
