// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VehiclePlatformPaymentsAdapter is an autogenerated mock type for the VehiclePlatformPaymentsAdapter type
type VehiclePlatformPaymentsAdapter struct {
	mock.Mock
}

// GeneratePayment provides a mock function with given fields: ctx, amount, status
func (_m *VehiclePlatformPaymentsAdapter) GeneratePayment(ctx context.Context, amount float64, status string) (string, error) {
	ret := _m.Called(ctx, amount, status)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, string) (string, error)); ok {
		return rf(ctx, amount, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, string) string); ok {
		r0 = rf(ctx, amount, status)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, string) error); ok {
		r1 = rf(ctx, amount, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVehiclePlatformPaymentsAdapter creates a new instance of VehiclePlatformPaymentsAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehiclePlatformPaymentsAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehiclePlatformPaymentsAdapter {
	mock := &VehiclePlatformPaymentsAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
