// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VehiclePlatformPaymentsHttpClient is an autogenerated mock type for the VehiclePlatformPaymentsHttpClient type
type VehiclePlatformPaymentsHttpClient struct {
	mock.Mock
}

// GeneratePayment provides a mock function with given fields: ctx, amount
func (_m *VehiclePlatformPaymentsHttpClient) GeneratePayment(ctx context.Context, amount float64) (string, error) {
	ret := _m.Called(ctx, amount)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64) (string, error)); ok {
		return rf(ctx, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64) string); ok {
		r0 = rf(ctx, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64) error); ok {
		r1 = rf(ctx, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVehiclePlatformPaymentsHttpClient creates a new instance of VehiclePlatformPaymentsHttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehiclePlatformPaymentsHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehiclePlatformPaymentsHttpClient {
	mock := &VehiclePlatformPaymentsHttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
